### ISSUE TITLE
CIC CRC: Deidentified Report - missing data

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1567]
In CIC CRC v1.29 (RDRF v6.2.0).
When comparing data in the Deidentified Report CSV to data in the CIC CRC system, much of the data is missing from the CSV. Most of the information for the first-listed patient (ID: staging-crc-333b429c-f88c-11ea-b02f-0242ac110009) is correctly recorded in the CSV, but the data for any multiple-select CDE is not recorded whatsoever, e.g. the comorbidities selection (`BaselineClinicalForm_1_medicalhistory_1_COMORBID`) in column CQ is completely blank, but multiple selections have been made in CIC CRC.

The data for all other patients is either sparse or missing completely from the CSV. For example, the second-listed patient (ID: staging-crc-40de1f9e-cbbb-11ea-ae4f-0242ac110010) only has data recorded for two of the questions for Baseline PROMS (`BaselineProms_1_Employment_1_Employ_type` & `BaselineProms_1_Employment_1_Employ_specific`, columns SS & ST respectively) - all other data is not present, despite the Baseline PROMS and all clinical forms having some data in CIC CRC.

**Comment by jithendralal** [comment]
- for multi-select check boxes, the values were not getting included in CSV, which is now fixed, but waiting for reply from Angela on the representation of the multi-select values in the CSV

**Comment by id2359** [comment]
Inbox
x

Angela Ives
10:52 AM (36 minutes ago)
to me

Yes, Lee

A

 

From: Lee Render <lrender@ccg.murdoch.edu.au>
Sent: Monday, 21 September 2020 10:27 AM
To: Angela Ives <angela.ives@uwa.edu.au>
Subject: Fwd: DeIdentified report - in csv format

 

Just on this : 

 

Are you ok with us transform multiselect checkbox answers into yes no vectors?

 

E.g.

 

If a a multiselect is 

Hatsize

[x ] Big

[ ] Medium

[ ] Small

 

then the column structure will be

 

Hatsize_Big Hatsize_Medium Hatsize_Small

Y                         N                           N

**Comment by jithendralal** [comment]
The modified CSV is attahed here as a .txt (as github does not allow .csv)
[staging-crc_20200917122654.txt](https://github.com/muccg/rdrf/files/5265369/staging-crc_20200917122654.txt)

The column names:
for all CDEs
form/1/section/1/cdeA, form/1/section/1/cdeB, ...

for multiselect CDEs
form/1/section/1/cdeM/valueA, form/1/section/1/cdeM/valueB, ...

multiselect CDEs will show Y or N in the CSV

**Comment by jithendralal** [comment]
[staging-crc_20200917122654.txt](https://github.com/muccg/rdrf/files/5308598/staging-crc_20200917122654.txt)
The modified csv.

**Comment by APMCCG** [comment]
Multiple-select CDE data is now recorded in the most recent CIC CRC Deidentified Report CSV, but data is still missing for patients. For example, the following patients (first 4 selected) all have data recorded in the Patient Information form in CIC CRC, but the columns containing Patient Information data (BQX-BSM) are blank:
staging-crc-40de1f9e-cbbb-11ea-ae4f-0242ac110010
staging-crc-40e14156-cbbb-11ea-ae4f-0242ac110010
staging-crc-40e3f2d4-cbbb-11ea-ae4f-0242ac110010
staging-crc-40fb8a20-cbbb-11ea-ae4f-0242ac110010

**Comment by jithendralal** [comment]
Having reset the data on CIC CRC staging, please test again with this CSV generated from the latest report:

**Comment by jithendralal** [comment]
The CSV generated after fixing the data missing issue:

[staging-crc_20201003081636.txt](https://github.com/muccg/rdrf/files/5325106/staging-crc_20201003081636.txt)
